version: "3.1"
services:
  testproject-agent:
    image: testproject/agent:latest
    container_name: testproject-agent
    depends_on:
      - chrome
      - firefox
    volumes:
      - /path/to/host/folder:/var/testproject/agent
    environment:
      TP_API_KEY: "6FAoQ5sxPVJLvU9Td50nMcW6sVWuGPrON-D5UExRYJk1"
      TP_JOB_ID: "xBxgAMJRlESuJnswDFrQvA"
      TP_JOB_PARAMS: '"jobParameters" : { "browsers" : ["Chrome"]}'
      CHROME: "chrome:4444"
      FIREFOX: "firefox:4444"
    secrets:
      - tp_agent
  chrome:
    image: selenium/standalone-chrome
    shm_size: '1gb'
    ports:
      - "4444:4444"
  firefox:
    image: selenium/standalone-firefox
    shm_size: '1gb'

secrets:
   tp_agent:
     file: /path/to/secrets.txt