name: Schedule Run Staging

on:
  schedule:
    - cron:  '40 0,11 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Testproject Job
        run: docker-compose -f docker-compose-github.yml up --abort-on-container-exit
